import * as icons from 'ionicons/icons';

export default [
    'alarm',
    'barbell',
    'bicycle',
    'book',
    'car',
    'construct',
    'cut',
    'dice',
    'fitness',
    'film',
    'flag',
    'flame',
    'footsteps',
    'glasses',
    'headset',
    'heart',
    'hourglass',
    'library',
    'moon',
    'musicalNotes',
    'newspaper',
    'nutrition',
    'paw',
    'person',
    'pint',
    'restaurant',
    'rose',
    'school',
    'shirt',
    'terminal',
    'train',
    'wallet',
    'water',
].map((name: string) => ({
    name,
    icon: (icons as any)[name + 'Outline'],
}))